AWSTemplateFormatVersion: 2010-09-09
Description: AWS Certbot - ACM certbot autorenewal

Parameters:
  EcrRepositoryUri:
    Type: String

  DnsCloudflareApiToken:
    Type: String
    NoEcho: true

  DomainList:
    Type: String

  DomainEmail:
    Type: String

  DaysBeforeExpiration:
    Type: String

  Timestamp:
    Type: String

Resources:
  AwsCertbotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Allow-logs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: arn:aws:logs:*:*:*
        - PolicyName: ACMGetImportCerts
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "acm:DescribeCertificate"
                  - "acm:ListCertificates"
                  - "acm:ImportCertificate"
                Resource: "*"

  AwsCertbotFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Request and Renew Certs in ACM
      PackageType: Image
      Role:
        Fn::GetAtt: ["AwsCertbotRole", "Arn"]
      Environment:
        Variables:
          DNS_CLOUDFLARE_API_TOKEN: !Ref DnsCloudflareApiToken
          DOMAIN_EMAIL: !Ref DomainEmail
          DOMAIN_LIST: !Ref DomainList
          DAYS_BEFORE_EXPIRATION: !Ref DaysBeforeExpiration
      Timeout: 120
      MemorySize: 512
      Code:
        ImageUri: !Sub "${EcrRepositoryUri}:latest"

  AwsCertbotFunctionEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: "Invoke AwsCertbotFunction"
      ScheduleExpression: "rate(1 day)"
      State: "ENABLED"
      Targets:
        - Arn:
            Fn::GetAtt:
              - "AwsCertbotFunction"
              - "Arn"
          Id: "TargetAwsCertbotFunction"

  AwsCertbotFunctionEventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: "AwsCertbotFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "AwsCertbotFunctionEvent"
          - "Arn"
